@@startuml

  [*] --> SinEdicion

  SinEdicion --> Navegando : w/a/s/d

  state Navegando {
    [*] --> PosicionInicial
    PosicionInicial --> Arriba : w
    PosicionInicial --> Izquierda : a
    PosicionInicial --> Abajo : s
    PosicionInicial --> Derecha : d
    Arriba --> PosicionInicial : w
    Izquierda --> PosicionInicial : a
    Abajo --> PosicionInicial : s
    Derecha --> PosicionInicial : d
  }

  Navegando --> Editando : e

  state Editando {
    [*] --> IngresandoContenido
    IngresandoContenido --> ContenidoLargo : ingresarContenido
    ContenidoLargo --> IngresandoContenido : mostrarContenidoCorto
   
  }

  Editando --> Navegando : w/a/s/d
  Navegando --> Finalizada : q
  SinEdicion --> Finalizada : q

  Finalizada --> [*]

@@enduml
